#!/usr/bin/env python3
"""Emit the routing-test descriptions block from each SKILL.md frontmatter.

Reads `skills/*/SKILL.md`, extracts the `description:` field from the YAML
frontmatter, and writes a flat text block to `tests/routing/descriptions.md`
that the routing promptfoo config loads as a single `{{ skill_descriptions }}`
var.

Two modes:
  python3 scripts/extract-descriptions.py          # write the file
  python3 scripts/extract-descriptions.py --check  # exit 1 if file is stale

The --check mode runs from validate-skills.py — catches drift between SKILL.md
frontmatter and the routing config.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
OUT = REPO / "tests" / "routing" / "descriptions.md"

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def parse_description(text: str) -> str:
    m = FRONTMATTER.match(text)
    if not m:
        raise ValueError("no YAML frontmatter")
    body = m.group(1)
    # description: may span lines (folded scalar); grab until the next key or EOF
    lines = body.splitlines()
    desc: list[str] = []
    in_desc = False
    for line in lines:
        if line.startswith("description:"):
            in_desc = True
            rest = line[len("description:"):].strip()
            if rest:
                if rest.startswith('"'):
                    try:
                        rest = json.loads(rest)
                    except json.JSONDecodeError as error:
                        raise ValueError(f"invalid quoted description: {error}") from error
                elif rest.startswith("'") and rest.endswith("'"):
                    rest = rest[1:-1].replace("''", "'")
                elif rest in {">", ">-", ">+", "|", "|-", "|+"}:
                    rest = ""
                desc.append(rest)
            continue
        if in_desc:
            # frontmatter keys are at column 0; continuation is indented
            if line and not line[0].isspace() and ":" in line:
                break
            desc.append(line.strip())
    return " ".join(p for p in desc if p)


def render() -> str:
    blocks: list[str] = []
    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            continue
        desc = parse_description(skill_md.read_text())
        blocks.append(f"slug: {skill_dir.name}\ndescription: {desc}")
    header = (
        "<!-- AUTO-GENERATED by scripts/extract-descriptions.py — do not edit. -->\n"
        "<!-- Source: frontmatter `description:` field of each skills/*/SKILL.md. -->\n\n"
    )
    return header + "\n\n".join(blocks) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    new = render()
    if check:
        if not OUT.exists():
            print(f"{OUT} missing — run scripts/extract-descriptions.py", file=sys.stderr)
            return 1
        if OUT.read_text() != new:
            print(f"{OUT} stale — run scripts/extract-descriptions.py", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(new)
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
